[supabase]
url = "https://yeobfkbhomhfrgeduobb.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllb2Jma2Job21oZnJnZWR1b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTYwMzgsImV4cCI6MjA3MTA5MjAzOH0.2vbA5azquXrnt9j5MQojezJfc8zA65gk3g9mY6vipaI"
bucket = "ims-uploads"
